theme: black-and-light
relativeURLs: true
baseURL: /
title: Hugo Themes
author: Steve Francia
copyright: >-
  Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights
  reserved.
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 10
taxonomies:
  category: categories
  tag: tags
  series: series
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

module:
  imports:
    - path: github.com/SummittDweller/hugo-timeline
      mounts:
      - source: layouts
        target: layouts
      - source: static
        target: static